config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
  }

  devise_for :users, controllers: {
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations'
  }

  root to: 'homes#top'
  get "about" => "homes#about"

  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :post
  attachment :image
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :favorites, dependent: :destroy
  accepts_attachments_for :images, attachment: :image

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :company, presence: true
  validates :line, presence: true
  validates :series, presence: true
  validates :car, presence: true
  validates :place, presence: true
  validates :title, presence: true
  validates :date, presence: true

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true

  has_many :comments, dependent: :destroy
  attachment :profile_image

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :index]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    posts_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new
    @comment.body = comment_params[:comment]
    @comment.post_id = @post.id
    @comment.user_id = current_user.id
    @comment.save
    redirect_to post_path(@post)
  end

  def destroy
    Comment.find_by(id: params[:id], post_id: params[:post_id]).destroy
    redirect_to post_path(params[:post_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 before_action :authenticate_user! ,except: [:top, :index]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.company = params[:post][:company]
    @post.line = params[:post][:line]
    @post.series = params[:post][:series]
    @post.car = params[:post][:car]
    @post.title = params[:post][:title]
    @post.date = params[:post][:date]
    if @post.save
      redirect_to posts_path(@post.id)
    else
      render :new
    end
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to posts_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:company, :line, :series, :car, :place, :title, :date, :body, images_images: [])
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).reverse_order
  end

  def index
    @user = current_user
    @users = User.all
    @post = Post.new
    @posts = Post.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
</table>

<div class='row'>
  <% if current_user != user %>
    <% if current_user.following?(user) %>
      <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
    <% end %>
  <% else %>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user(current_user)" %>
  <% end %>

</div>

app/views/users/edit.html.erb
<div class='container bg-white col-md-5 my-4'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>プロフィール編集</h2>
    <%= form_with model:@user, local:true do |f| %>
     <div class="form-group">
       <%= f.label :"プロフィール画像" %>
       <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
     </div>
     <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="profile-container">
  <div class="container bg-white col-md-8 my-4">
  <div class="row">
    <div class="col-lg-4">
      <%= attachment_image_tag @user, :profile_image, size: "150x150", format: 'jpeg', fallback: "no_image.jpg" %>
       <h2 class="profile-name text-align my-3"><%= @user.name %></h2>
      <div class="my-3"><%= link_to "Follow:", user_followings_path(@user.id), class:"rounded-left border border-dark bg-light text-dark my-3", method: :get %>　<%= @user.followings.count %></div>
      <div class="my-3"><%= link_to "Follower:", user_followers_path(@user.id), class:"rounded-left border border-dark bg-light text-dark my-3", method: :get %>　<%= @user.followers.count %>
      </div>
      <% if @user.id != current_user.id %>
        <% if current_user.following?(@user) %>
        <%= link_to "Unfollow", user_relationships_path(@user.id), class:"btn btn-dark mt-3", method: :delete %>
        <% else %>
        <%= link_to "Follow", user_relationships_path(@user.id), class:"btn btn-secondary mt-3", method: :post %>
        <% end %>
      <% end %>
      <% if @user.id == current_user.id %>
       <%= link_to "プロフィール編集", edit_user_path(@user), class:"btn btn-outline-secondary" %>
      <% end %>
    </div>
    <div class="col-lg-8">
      <% @users.each do |user| %>
      <div class="card mb-3 border-dark" style="max-width: 540px;">
      <div class="row g-0">
        <div class="col-md-4">
            <%= link_to user_path(user.id) do %>
            <%= attachment_image_tag user, :profile_image, size: "140x140", fallback: "no_image.jpg" %>
            <% end %>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title"><%= user.name %></h5>
            <p class="card-text bg-light text-dark"><%= link_to "Follow:", user_followings_path(user.id), class:"bg-light text-dark", method: :get %>　<%= user.followings.count %></p>
            <p class="card-text bg-light text-dark"><%= link_to "Follower:", user_followers_path(user.id), class:"bg-light text-dark", method: :get %>　<%= user.followers.count %></p>
            <p class="card-text">
              <% if user.id != current_user.id %>
                <% if current_user.following?(user) %>
                <%= link_to "Unfollow", user_relationships_path(user.id), class:"btn btn-dark", method: :delete %>
                <% else %>
                <%= link_to "Follow", user_relationships_path(user.id), class:"btn btn-secondary", method: :post %>
                <% end %>
              <% end %>
            </p>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    </div>
  </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container bg-white col-md-8 my-4'>
  <div class='row'>
    <div class='col-lg-4'>
      <h2 class="text-center">User info</h2>
      <%= link_to users_path(current_user) do %>
      <%= render 'info', user: current_user %>
      <% end %>
    </div>
    <div class='col-md-8 text-center'>
      <h2 class="text-center">マイ投稿一覧</h2>
      <div class="row">
    <% @posts.each do |post| %>
    <div class="container">
     <%= link_to post_path(post.id) do %>
     <% if post.images.present? %>
          <% post.images.first(1).each do |image| %>
            <%= attachment_image_tag image, :image, :fill, 250, 180 %>
          <% end %>
        <% else %>
          <%= image_tag 'no_image.jpg', width: '70%', height: '70%' %>
        <% end %>
        <p class="link"><%= post.title %></p>
     <% end %>
     </div>
     <% end %>
    </div>
  </div>
</div>
</div>