config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
  }

  devise_for :users, controllers: {
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations'
  }

  root to: 'homes#top'
  get "about" => "homes#about"

  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :post
  attachment :image
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :favorites, dependent: :destroy
  accepts_attachments_for :images, attachment: :image

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :company, presence: true
  validates :line, presence: true
  validates :series, presence: true
  validates :car, presence: true
  validates :place, presence: true
  validates :title, presence: true
  validates :date, presence: true

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true

  has_many :comments, dependent: :destroy
  attachment :profile_image

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :index]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    posts_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new
    @comment.body = comment_params[:comment]
    @comment.post_id = @post.id
    @comment.user_id = current_user.id
    @comment.save
    redirect_to post_path(@post)
  end

  def destroy
    Comment.find_by(id: params[:id], post_id: params[:post_id]).destroy
    redirect_to post_path(params[:post_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 before_action :authenticate_user! ,except: [:top, :index]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.company = params[:post][:company]
    @post.line = params[:post][:line]
    @post.series = params[:post][:series]
    @post.car = params[:post][:car]
    @post.title = params[:post][:title]
    @post.date = params[:post][:date]
    if @post.save
      redirect_to posts_path(@post.id)
    else
      render :new
    end
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to posts_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:company, :line, :series, :car, :place, :title, :date, :body, images_images: [])
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).reverse_order
  end

  def index
    @user = current_user
    @users = User.all
    @post = Post.new
    @posts = Post.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/edit.html.erb
<div class="container bg-white col-md-5 my-4">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1 class="title">編集画面</h1>
  <div class="form_post">
    <%= form_with model:@post, url: post_path, local:true do |f|%>
      <div class="form-group">
        <%= f.label :"タイトル" %><br />
        <%= f.text_field :title, autofocus: true, class: "text_field" %>
      </div>
      <div class="form-group">
        <%= f.label :"会社名" %><br />
        <%= f.text_field :company, autofocus: true, class: "text_field" %>
      </div>
      <div class="form-group">
        <%= f.label :"形式" %><br />
        <%= f.text_field :series, autofocus: true, class: "text_field" %>
      </div>
      <div class="form-group">
        <%= f.label :"路線名" %><br />
        <%= f.text_field :line, autofocus: true, class: "text_field" %>
      </div>
      <div class="form-group">
        <%= f.label :"編成" %><br />
        <%= f.text_field :car, autofocus: true, class: "text_field" %>
      </div>
      <div class="form-group">
        <%= f.label :"場所" %><br />
        <%= f.text_field :place, autofocus: true, class: "text_field" %>
      </div>
      <div class="form-group">
        <%= f.label :"本文" %><br />
        <%= f.text_area :body, class: "form-control body" %>
      </div>
      <div class="form-group">
        <%= f.label :"撮影日時" %><br />
        <%= f.text_field :date, autofocus: true, class: "text_field" %>
      </div>
      <div class="form-group">
        <%= f.label :"画像" %><br />
        <%= f.attachment_field :images_images, multiple: true %>
      </div>
      <%= f.submit '訂正', class: "btn btn-info" %>
    <% end %>
    <td><%= link_to "投稿詳細へ戻る", post_path, class: "btn btn-danger" %></td>
    <td><%= link_to "削除", post_path, method: :delete, class: "btn btn-primary", data: { confirm: 'Are you sure?' } %></td>
  </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class='container bg-white col-md-8 my-4'>
  <div class='row'>
    <div class='col-md-4'>
      <h2 class="text-center">User info</h2>
      <%= link_to users_path(current_user) do %>
      <%= render 'users/info', user: current_user %>
      <% end %>
    </div>
    <div class='col-md-8 text-center'>
        <% @posts.each do |post| %>
        <%= link_to post_path(post.id) do %>
  <% if post.images.present? %>
  <% post.images.first(1).each do |image| %>
            <%= attachment_image_tag image, :image, :fill, 250, 180 %>
          <% end %>
        <% else %>
          <%= image_tag 'no_image.jpg', width: '200', height: '200' %>
        <% end %>
      <div class="show-contents text-center">
      <div class="show-details">
        <p class="show-text">タイトル</p>
        <p class="show-text bold"><%= post.title %></p>
        <p class="show-text">路線名</p>
        <p class="show-text bold"><%= post.line %></p>
        <p class="show-text">会社名</p>
        <p class="show-text bold"><%= post.company %></p>
        <p class="show-text">形式</p>
        <p class="show-text bold"><%= post.series %></p>
        <p class="show-text">編成</p>
        <p class="show-text bold"><%= post.car %></p>
        <p class="show-text">場所</p>
        <p class="show-text bold"><%= post.place %></p>
        <p class="show-text">撮影年月日</p>
        <p class="show-text bold"><%= post.date %></p>
        <p class="show-text">本文</p>
        <p class="show-text bold"><%= post.body %></p>
        <p class="show-text">投稿年月日</p>
        <p class="show-text bold"><%= post.created_at.strftime('%Y/%m/%d') %></p>
        <% if post.user == current_user %>
        <td><%= link_to "編集",edit_post_path(post), class: "btn btn-warning" %></td>
        <td><%= link_to "削除",post_path(post), method: :delete, class: "btn btn-primary", data: { confirm: "削除してよろしいですか？" } %></td>
        <% end %>
      </div>
    </div>
  <% end %>
  <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container bg-white col-md-5 my-4">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2 class="text-center">新規投稿</h2>
        <% if @post.errors.any? %>
        <%= @post.errors.count %>件のエラーが発生しました
        <% @post.errors.full_messages.each do |message| %>
        <%= message %>
        <% end %>
        <% end %>
        <%= form_with model: @post, local: true do |f| %>
        <div class="form-group">
          <%= f.label :images_images, "画像" %><br>
          <%= f.attachment_field :images_images, multiple: true,  class:"form-image" %>
        </div>
        <div class="form-group">
          <%= f.label :company, "会社名" %><br>
          <%= f.text_field :company, multiple: true %>
        </div>
        <div class="form-group">
          <%= f.label :line, "路線名" %><br>
          <%= f.text_field :line, multiple: true %>
        </div>
        <div class="form-group">
          <%= f.label :series, "形式" %><br>
          <%= f.text_field :series, multiple: true %>
        </div>
        <div class="form-group">
          <%= f.label :car, "編成" %><br>
          <%= f.text_field :car, multiple: true %>
        </div>
        <div class="form-group">
          <%= f.label :place, "場所" %><br>
          <%= f.text_field :place, class: "form-control place" %>
        </div>
        <div class="form-group">
          <%= f.label :title, "タイトル" %><br>
          <%= f.text_field :title, multiple: true %>
        </div>
        <div class="form-group">
          <%= f.label :date, "撮影年月日" %><br>
          <%= f.text_field :date, multiple: true %>
        </div>
        <div class="form-group">
          <%= f.label :body, "本文" %><br>
          <%= f.text_area :body, class: "form-control body" %>
        </div>
        <div class="form-detail">
        <%= f.submit :"投稿する", class:"btn btn-success"  %>
      </div>
        <% end %>
      </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container bg-white col-md-10 my-4">
  <div class="row">
    <div class="show-container col-md-8 mx-auto">
    <div class="show-image">
      <% if @post.images.present? %>
      <% @post.images.each do |image| %>
      <%= attachment_image_tag image, :image, class:"show-images" %>
      <% end %>
      <% else %>
      <%= image_tag 'no_image.jpg', size: '200x200' %>
      <% end %>
    </div>
    <div class="show-contents">
      <div class="show-details">
        <p class="show-text">タイトル</p>
        <p class="show-text bold"><%= @post.title %></p>
        <p class="show-text">路線名</p>
        <p class="show-text bold"><%= @post.line %></p>
        <p class="show-text">会社名</p>
        <p class="show-text bold"><%= @post.company %></p>
        <p class="show-text">形式</p>
        <p class="show-text bold"><%= @post.series %></p>
        <p class="show-text">編成</p>
        <p class="show-text bold"><%= @post.car %></p>
        <p class="show-text">場所</p>
        <p class="show-text bold"><%= @post.place %></p>
        <p class="show-text">撮影年月日</p>
        <p class="show-text bold"><%= @post.date %></p>
        <p class="show-text">本文</p>
        <p class="show-text bold"><%= @post.body %></p>
        <p class="show-text">投稿年月日</p>
        <p class="show-text bold"><%= @post.created_at.strftime('%Y/%m/%d') %></p>
        <% if @post.user == current_user %>
        <td><%= link_to "編集",edit_post_path(@post), class: "btn btn-warning" %></td>
        <td><%= link_to "削除",post_path(@post), method: :delete, class: "btn btn-primary", data: { confirm: "削除してよろしいですか？" } %></td>
        <% end %>
      </div>
    </div>
  </div>
  
  
  <div class="comment">
    <div class="comment-title">
      <h2>コメント</h2>
      <p class="comment-count">(<%= @post.comments.count %>)</p>
    </div>
    <div class="comment-contents">
      <% @post.comments.each do |comment| %>
      <div class="comment-index">
        <p class="comment-icon"><%= attachment_image_tag comment.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", class:"profile-image" %></p>
        <p class="comment-details"><%= comment.user.name %></p>
        <p class="comment-details"><%= comment.created_at.strftime('%Y/%m/%d') %></p>
        <p class="comment-body"><%= comment.body %></p>
        <div class="comment-details">
          <% if comment.user == current_user %>
            <%= link_to "削除", post_comment_path(comment.post, comment), class: "btn btn-primary", method: :delete %>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
  </div>

  <div class="comment-new">
    <%= form_with(model:[@post, @comment], local: true) do |f| %>
      <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに", class: "comment-form" %>
      <%= f.submit "送信する", class:"btn btn-success" %>
    <% end %>
  </div>
  <% if @post.favorited_by?(current_user) %>
    <p>
      <%= link_to post_favorites_path(@post), method: :delete do %>
        ♥<%= @post.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to post_favorites_path(@post), method: :post do %>
        ♡<%= @post.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>
</div>
</div>